services:
  - type: web
    name: financial-portfolio
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn financial_portfolio.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: financial_portfolio
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"