# Generated by Django 5.0.4 on 2025-02-09 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_institution', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=10)),
                ('asset', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('rate', models.FloatField()),
                ('maturity_date', models.DateField()),
                ('amount', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
